import Application from "../models/Application.js";
import { extractResumeText } from "../services/resumeParser.js";
import { matchCandidateToJobs } from "../services/matchCandidateToJobs.js";
import { uploadResumeToCloudinary } from "../services/uploadResume.js";
import { Resend } from "resend";
import fs from "fs";

const resend = new Resend(process.env.RESEND_API_KEY);

export const createApplication = async (req, res) => {
  const file = req.file;
  if (!file) {
    return res.status(400).json({ error: "Resume file is required" });
  }
  let resUrl = null;

    // NEW: upload file if present
    if (req.file) {
      const uploadResult = await uploadResumeToCloudinary(req.file.path);
      resUrl = uploadResult.url;
    }

  const filePath = file.path;
  try {
    const resume = await extractResumeText(filePath);
    const application = await Application.create({
      name: req.body.name,
      phone: req.body.phone,
      email: req.body.email,
      experience: req.body.experience,
      currentSalary: req.body.currentSalary,
      expectedSalary: req.body.expectedSalary,
      function: req.body.functionCategory,
      subFunction: req.body.subFunction,
      resumeText: resume,
      resumeURL: resUrl
    });
    res.status(201).json(application);
  } catch (err) {
    console.error("Create application error:", err);
    res.status(500).json({ error: err.message });
  }
  finally {
    if (filePath && fs.existsSync(filePath)) {
      fs.unlink(filePath, (err) => {
        if (err) {
          console.error("File delete error:", err.message);
        } else {
          console.log("Temp file deleted:", filePath);
        }
      });
    }
  }
};


export const matchJobsForCandidate = async (req, res) => {
  try {
    const { applicationId } = req.params;

    const results = await matchCandidateToJobs(applicationId);
    const candidate = await Application.findById(applicationId);

    const filteredResults = results.filter(r => r.score >= 70);
    const jobList = filteredResults
      .map((r, i) => `${i + 1}. ${r.job.title} - Score: ${r.score.toFixed(2)} - Feedback: ${r.feedback}`)
      .join("\n\n");

    if (filteredResults.length > 0) {
        // Email content
        const generateChartUrl = (score) => {
  const rounded = Math.round(score);

  const chartConfig = {
    type: "doughnut",
    data: {
      datasets: [
        {
          data: [rounded, 100 - rounded],
          backgroundColor: ["#16a34a", "#e5e7eb"]
        }
      ]
    },
    options: {
      cutout: "70%",
      plugins: {
        legend: { display: false }
      }
    }
  };

  return `https://quickchart.io/chart?c=${encodeURIComponent(
    JSON.stringify(chartConfig)
  )}`;
};

const jobCards = filteredResults.map((r, i) => `
  <div style="border:1px solid #e5e7eb;border-radius:10px;padding:16px;margin-bottom:16px;">
    
    <h3 style="margin:0 0 8px 0;color:#111827;">
      ${i + 1}. ${r.job.title}
    </h3>

    <img src="${generateChartUrl(Math.round(r.score))}" 
         style="width:120px;height:120px;display:block;margin:10px auto;" />

    <p style="text-align:center;font-weight:bold;color:#16a34a;">
      ${r.score.toFixed(1)}% Match
    </p>

    <p style="color:#374151;font-size:14px;">
      ${r.feedback}
    </p>
  </div>
`).join("");

const emailHtml = `
<div style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px;">

  <div style="max-width:600px;margin:auto;background:white;border-radius:12px;padding:24px;">

    <h2 style="margin:0;color:#111827;">
    High Match Candidate Identified
    </h2>

    <hr style="margin:16px 0;border:none;border-top:1px solid #e5e7eb;" />

    <h3 style="margin-bottom:8px;">Candidate</h3>
    <p style="margin:4px 0;"><strong>Name:</strong> ${candidate.name}</p>
    <p style="margin:4px 0;"><strong>Email:</strong> ${candidate.email}</p>

    <div style="margin:16px 0;">
      <a href="${candidate.resumeURL || '#'}"
         style="display:inline-block;padding:10px 16px;background:#2563eb;color:white;text-decoration:none;border-radius:6px;">
         View Resume
      </a>
    </div>

    <h3>Matched Jobs</h3>

    ${jobCards}

    <hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb;" />

    <p style="font-size:12px;color:#6b7280;text-align:center;">
      Generated by CORE Hiring Engine
    </p>

  </div>
</div>
`;

        
        try {
          await resend.emails.send({
            from: "Core Team <no-reply@careersatcore.com>",
            to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
            subject: `New Candidate Match: ${candidate.name}`,
            html: emailHtml
          });
      } catch (err) {
        console.error("Mail failed:", err.message);
      }
    }
    if (filteredResults.length == 0) {
        // Email content
        const emailHtml = `
<div style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px;">

  <div style="max-width:600px;margin:auto;background:white;border-radius:12px;padding:24px;">

    <h2 style="color:#111827;">New Candidate Profile</h2>

    <hr style="margin:16px 0;" />

    <p><strong>Name:</strong> ${candidate.name}</p>
    <p><strong>Email:</strong> ${candidate.email}</p>
    <p><strong>Experience:</strong> ${candidate.experience} years</p>
    <p><strong>Current Salary:</strong> ${candidate.currentSalary} LPA</p>
    <p><strong>Expected Salary:</strong> ${candidate.expectedSalary} LPA</p>
    <p><strong>Function:</strong> ${candidate.function}</p>
    <p><strong>Sub-Function:</strong> ${candidate.subFunction}</p>

    <div style="margin:16px 0;">
      <a href="${candidate.resumeURL || '#'}"
         style="display:inline-block;padding:10px 16px;background:#2563eb;color:white;text-decoration:none;border-radius:6px;">
         View Resume
      </a>
    </div>

    <div style="padding:12px;background:#fef3c7;border-radius:8px;color:#92400e;">
      No strong matches found for this candidate yet.
    </div>

    <hr style="margin:24px 0;" />

    <p style="font-size:12px;color:#6b7280;text-align:center;">
      Generated by CORE Hiring Engine
    </p>

  </div>
</div>
`;
        
        try {
          const response = await resend.emails.send({
            from: "Core Team <no-reply@careersatcore.com>",
            to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
            subject: `New Candidate: ${candidate.name}`,
            html: emailHtml
          });
          console.log("Resend response:", response);
      } catch (err) {
        console.error("Mail failed:", err.message);
      }
    }


    res.json({
      count: results.length,
      matches: results.map(r => ({
        jobId: r.job._id,
        title: r.job.title,
        score: r.score,
        feedback: r.feedback
      }))
    });

  } catch (err) {
    console.error("Candidate match error:", err);
    res.status(500).json({ error: err.message });
  }
};