import Application from "../models/Application.js";
import { extractResumeText } from "../services/resumeParser.js";
import { matchCandidateToJobs } from "../services/matchCandidateToJobs.js";
import { sendMail } from "../services/gmailService.js";
import { uploadResumeToCloudinary } from "../services/uploadResume.js";
import fs from "fs";

export const createApplication = async (req, res) => {
  const file = req.file;
  if (!file) {
    return res.status(400).json({ error: "Resume file is required" });
  }
  let resUrl = null;

    // NEW: upload file if present
    if (req.file) {
      const uploadResult = await uploadResumeToCloudinary(req.file.path);
      resUrl = uploadResult.url;
    }

  const filePath = file.path;
  try {
    const resume = await extractResumeText(filePath);
    const application = await Application.create({
      name: req.body.name,
      phone: req.body.phone,
      email: req.body.email,
      experience: req.body.experience,
      salary: req.body.salary,
      function: req.body.functionCategory,
      subFunction: req.body.subFunction,
      resumeText: resume,
      resumeURL: resUrl
    });
    res.status(201).json(application);
  } catch (err) {
    console.error("Create application error:", err);
    res.status(500).json({ error: err.message });
  }
  finally {
    if (filePath && fs.existsSync(filePath)) {
      fs.unlink(filePath, (err) => {
        if (err) {
          console.error("File delete error:", err.message);
        } else {
          console.log("Temp file deleted:", filePath);
        }
      });
    }
  }
};


export const matchJobsForCandidate = async (req, res) => {
  try {
    const { applicationId } = req.params;

    const results = await matchCandidateToJobs(applicationId);
    const candidate = await Application.findById(applicationId);

    const filteredResults = results.filter(r => r.score >= 70);
    const jobList = filteredResults
      .map((r, i) => `${i + 1}. ${r.job.title} - Score: ${r.score.toFixed(2)} - Feedback: ${r.feedback}`)
      .join("\n\n");

    if (filteredResults.length > 0) {
        // Email content
        const emailText = `
        New Candidate Match Found

        Candidate Details:
        Name: ${candidate.name}
        Email: ${candidate.email}

        Resume:
        ${candidate.resumeURL ? candidate.resumeURL : "No resume URL available"}

        Matched Jobs:
        ${jobList}

        ----------------------
        Generated by CORE system
        `;

        
        try {
          await sendMail({
            to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
            subject: `New Candidate Match: ${candidate.name}`,
            text: emailText
          });
      } catch (err) {
        console.error("Mail failed:", err.message);
      }
    }
    if (filteredResults.length == 0) {
        // Email content
        const emailText = `
        New Candidate Found

        Candidate Details:
        Name: ${candidate.name}
        Email: ${candidate.email}

        Resume:
        ${candidate.resumeURL ? candidate.resumeURL : "No resume URL available"}
        No strong matches found for this candidate.

        ----------------------  
        Generated by CORE system
        `;

        
        try {
          await sendMail({
            to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
            subject: `New Candidate: ${candidate.name}`,
            text: emailText
          });
      } catch (err) {
        console.error("Mail failed:", err.message);
      }
    }


    res.json({
      count: results.length,
      matches: results.map(r => ({
        jobId: r.job._id,
        title: r.job.title,
        score: r.score,
        feedback: r.feedback
      }))
    });

  } catch (err) {
    console.error("Candidate match error:", err);
    res.status(500).json({ error: err.message });
  }
};