import User from "../models/User.js";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import { Resend } from "resend";

console.log("[AuthController] INFO: Auth controller loaded");

// SIGNUP
export const signup = async (req, res) => {
  console.log("[AuthController] INFO: signup called with email:", req.body?.email);
  try {
    const {
      name,
      email,
      password,
      phone,
      companyName,
      companyType,
      companySize,
      companyRole
    } = req.body;

    if (!email || !password || !name) {
      console.warn("[AuthController] WARNING: Missing required fields");
      return res.status(400).json({ error: "Name, email, and password are required" });
    }

    const existing = await User.findOne({ email });
    if (existing) {
      console.warn("[AuthController] WARNING: User already exists:", email);
      return res.status(400).json({ error: "User already exists" });
    }
    console.log("[AuthController] INFO: Hashing password");
    const hashed = await bcrypt.hash(password, 10);
    console.log("[AuthController] INFO: Creating user in database");
    const user = await User.create({
      name,
      email,
      password: hashed,
      phone,
      companyName,
      companyType,
      companySize,
      companyRole
    });
    console.log("[AuthController] INFO: User created successfully, ID:", user._id);
    const emailHtml = `
<div style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px;">

  <div style="max-width:600px;margin:auto;background:white;border-radius:12px;padding:24px;">

    <h2 style="color:#111827;">New User Created</h2>

    <hr style="margin:16px 0;" />

    <h3 style="margin-bottom:8px;">${user.name}</h3>
    <p><strong>Email:</strong> ${user.email}</p>
    <p><strong>Phone:</strong> ${user.phone || "N/A"}</p>
    <p><strong>Company name:</strong> ${user.companyName || "N/A"}</p>
    <p><strong>Company type:</strong> ${user.companyType || "N/A"}</p>
    <p><strong>Company size:</strong> ${user.companySize || "N/A"}</p>
    <p><strong>Role in companu:</strong> ${user.companyRole || "N/A"}</p>

    <hr style="margin:24px 0;" />

    <p style="font-size:12px;color:#6b7280;text-align:center;">
      Generated by CORE Hiring Engine
    </p>

  </div>
</div>
`;
            try {
              await resend.emails.send({
                from: "Core Team <no-reply@careersatcore.com>",
                to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
                subject: `New User: ${user.name}`,
                html: emailHtml
              });
          } catch (err) {
            console.error("Mail failed:", err.message);
          } 
    res.json({ message: "User created" });
  } catch (err) {
    console.error("[AuthController] ERROR: Signup failed:", err.message);
    console.error("[AuthController] STACK:", err.stack);
    res.status(500).json({ error: err.message });
  }
};

// LOGIN
export const login = async (req, res) => {
  console.log("[AuthController] INFO: login called with email:", req.body?.email);
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      console.warn("[AuthController] WARNING: Missing email or password");
      return res.status(400).json({ error: "Email and password are required" });
    }

    const user = await User.findOne({ email });
    if (!user) {
      console.warn("[AuthController] WARNING: User not found:", email);
      return res.status(400).json({ error: "User not found" });
    }

    const match = await bcrypt.compare(password, user.password);
    if (!match) {
      console.warn("[AuthController] WARNING: Invalid password for user:", email);
      return res.status(400).json({ error: "Invalid password" });
    }
    console.log("[AuthController] INFO: Generating JWT token");
    const token = jwt.sign(
      { id: user._id, email: user.email, role: user.role },
      process.env.JWT_SECRET,
      { expiresIn: "7d" }
    );

    console.log("[AuthController] INFO: Setting cookie");
    res.cookie("token", token, {
      httpOnly: true,
      secure: true,          // 🔥 MUST (Railway = HTTPS)
      sameSite: "none",      // 🔥 CRITICAL FIX
      maxAge: 7 * 24 * 60 * 60 * 1000
    });
    console.log("[AuthController] INFO: Login successful for user:", email);
    res.json({ message: "Logged in" });
  } catch (err) {
    console.error("[AuthController] ERROR: Login failed:", err.message);
    console.error("[AuthController] STACK:", err.stack);
    res.status(500).json({ error: err.message });
  }
};

// ADMIN LOGIN
export const adminLogin = async (req, res) => {
    console.log("[AuthController] INFO: adminLogin called with email:", req.body?.email);
  try {
    const { email, password } = req.body;

    const user = await User.findOne({ email });
    if (!user) {
      console.warn("[AuthController] WARNING: User not found:", email);
      return res.status(400).json({ error: "User not found" });
    }

    if (user.role !== "admin") {
      console.warn("[AuthController] WARNING: User is not an admin:", email);
      return res.status(403).json({ error: "Not an admin" });
    }

    const match = await bcrypt.compare(password, user.password);
    if (!match) {
      console.warn("[AuthController] WARNING: Invalid password for user:", email);
      return res.status(400).json({ error: "Invalid password" });
    }
    console.log("[AuthController] INFO: Generating JWT token");


    const token = jwt.sign(
      { id: user._id, email: user.email, role: user.role },
      process.env.JWT_SECRET,
      { expiresIn: "7d" }
    );

    res.cookie("token", token, {
      httpOnly: true,
      secure: true,
      sameSite: "none",
      maxAge: 7 * 24 * 60 * 60 * 1000
    });
    console.log("[AuthController] INFO: Admin login successful for user:", email);
    res.json({ message: "Admin logged in" });

  } catch (err) {
    console.error("[AuthController] ERROR: Admin login failed:", err.message);
    console.error("[AuthController] STACK:", err.stack);
    res.status(500).json({ error: err.message });
  }
};

// LOGOUT
export const logout = (req, res) => {
  console.log("[AuthController] INFO: logout called");
  res.clearCookie("token", {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production"
  });
  console.log("[AuthController] INFO: Logout successful");
  res.json({ message: "Logged out" });
};

// GET CURRENT USER
export const me = (req, res) => {
  console.log("[AuthController] INFO: me called, user:", req.user?.id);
  res.json({ user: req.user });
};