import Job from "../models/Job.js";
import StagingJob from "../models/StagingJob.js";
import PairedScore from "../models/PairedScores.js";
import fs from "fs";
import { parseJobDescription } from "../services/aiService.js";
import { extractResumeText } from "../services/resumeParser.js";
import { matchJobToCandidates } from "../services/matchJobToCandidates.js";
import { sendMail } from "../services/gmailService.js";

export const createJob = async (req, res) => {
  const file = req.file;
  const selectedFunction = req.body.function;
  if (!file) {
    return res.status(400).json({ error: "Job description file is required" });
  }
  const filePath = file.path;

  try {
    // Step 1: Extract raw text
    const description = await extractResumeText(filePath);

    // Step 2: Parse the job description with AI
    let parsed = {};
    try {
      parsed = await parseJobDescription(description);
      if (Array.isArray(parsed.requirements)) {
        parsed.requirements = parsed.requirements.map(r =>
          typeof r === "object" ? JSON.stringify(r) : r
        );
      }
    } catch (err) {
      console.error("Parsing failed:", err.message);
      parsed = {
        title: "Unknown",
        requirements: [],
        responsibilities: [],
        experienceMin: null,
        experienceMax: null,
        salaryMin: null,
        salaryMax: null,
        function: null
      };
    }
    if (selectedFunction) {
      parsed.function = selectedFunction;
    }
    // Step 3: Save to DB once with all data
    const job = await StagingJob.create({
      ...parsed,
      description,
      recruiterId: req.user.id,
      formFields: [
        { label: "Full Name", type: "text", required: true },
        { label: "Email", type: "email", required: true },
        { label: "Resume", type: "file", required: true }
      ]
    });
    res.status(201).json(job);

    const emailText = `
New Job Uploaded

Title: ${job.title}
Function: ${job.function || "N/A"}
Experience: ${job.experienceMin || "N/A"} - ${job.experienceMax || "N/A"} years
Salary: ${job.salaryMin || "N/A"} - ${job.salaryMax || "N/A"} LPA
----------------------
Generated by CORE system
`;
            try {
              await sendMail({
                to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
                subject: `New Job: ${job.title}`,
                text: emailText
              });
          } catch (err) {
            console.error("Mail failed:", err.message);
          } 

  } catch (err) {
    console.error("ERROR:", err);
    res.status(500).json({ error: err.message });
  } finally {
    if (filePath && fs.existsSync(filePath)) {
      fs.unlink(filePath, (err) => {
        if (err) console.error("File delete error:", err.message);
        else console.log("Temp file deleted:", filePath);
      });
    }
  }
};

export const matchCandidatesForJob = async (req, res) => {
  try {
    const { jobId } = req.params;

    const results = await matchJobToCandidates(jobId);

    res.json({
      count: results.length,
      matches: results.map(r => ({
        applicationId: r.candidate._id,
        name: r.candidate.name,
        email: r.candidate.email,
        score: r.score,
        feedback: r.feedback,
        resumeUrl: r.candidate.resumeURL,
        resumeText: r.candidate.resumeText
      }))
    });

  } catch (err) {
    console.error("Job match error:", err);
    res.status(500).json({ error: err.message });
  }
};

export const getAllJobs = async (req, res) => {
  try {
    const jobs = await Job.find().sort({ createdAt: -1 });
    res.json(jobs);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

export const deleteJob = async (req, res) => {
  try {
    const { jobId } = req.params;

    const job = await Job.findByIdAndDelete(jobId);

    if (!job) {
      return res.status(404).json({ error: "Job not found" });
    }

    await PairedScore.deleteMany({ jobId });
    res.json({
      message: "Job deleted successfully",
      jobId
    });

  } catch (err) {
    console.error("Delete job error:", err);
    res.status(500).json({ error: err.message });
  }
};

export const getMyJobs = async (req, res) => {
  try {
    const jobs = await Job.find({
      recruiterId: req.user.id
    }).sort({ createdAt: -1 });

    res.json(jobs);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};