import Job from "../models/Job.js";
import StagingJob from "../models/StagingJob.js";
import PairedScore from "../models/PairedScores.js";
import Test from "../models/Test.js";
import fs from "fs";
import { parseJobDescription } from "../services/aiService.js";
import { extractResumeText } from "../services/resumeParser.js";
import { matchJobToCandidates } from "../services/matchJobToCandidates.js";
import { generateTestFromJD } from "../services/generateTest.js";
import { Resend } from "resend";

const extractAndNormalizeSalary = (value) => {
    if (!value) return "";

    let str = value.toString().toLowerCase().replace(/,/g, "").trim();

    const match = str.match(/\d+(\.\d+)?/);
    if (!match) return "";

    let num = parseFloat(match[0]);

    // If already in LPA format
    if (str.includes("lpa") || str.includes("lac") || str.includes("lakh")) {
      return num;
    }

    // If value looks like full INR (no label)
    if (num >= 100000) {
      return num / 100000; // convert to LPA
    }

    // Already small → assume LPA
    return num;
  };

export const createJob = async (req, res) => {
  const file = req.file;
  const resend = new Resend(process.env.RESEND_API_KEY);
  const selectedFunction = req.body.function;
  if (!file) {
    return res.status(400).json({ error: "Job description file is required" });
  }
  const filePath = file.path;

  try {
    // Step 1: Extract raw text
    const description = await extractResumeText(filePath);

    // Step 2: Parse the job description with AI
    let parsed = {};
    try {
      parsed = await parseJobDescription(description);
      if (Array.isArray(parsed.requirements)) {
        parsed.requirements = parsed.requirements.map(r =>
          typeof r === "object" ? JSON.stringify(r) : r
        );
      }
    } catch (err) {
      console.error("Parsing failed:", err.message);
      parsed = {
        title: "Unknown",
        requirements: [],
        responsibilities: [],
        experienceMin: null,
        experienceMax: null,
        salaryMin: null,
        salaryMax: null,
        function: null
      };
    }
    if (selectedFunction) {
      parsed.function = selectedFunction;
    }

    parsed.salaryMin = extractAndNormalizeSalary(parsed.salaryMin);
    parsed.salaryMax = extractAndNormalizeSalary(parsed.salaryMax);
    // Step 3: Save to DB once with all data
    const job = await StagingJob.create({
      ...parsed,
      description,
      recruiterId: req.user.id,
      formFields: [
        { label: "Full Name", type: "text", required: true },
        { label: "Email", type: "email", required: true },
        { label: "Resume", type: "file", required: true }
      ]
    });
      

    res.status(201).json(job);

    const emailHtml = `
<div style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px;">

  <div style="max-width:600px;margin:auto;background:white;border-radius:12px;padding:24px;">

    <h2 style="color:#111827;">New Job Created</h2>

    <hr style="margin:16px 0;" />

    <h3 style="margin-bottom:8px;">${job.title}</h3>

    <p><strong>Function:</strong> ${job.function || "N/A"}</p>
    <p><strong>Experience:</strong> ${job.experienceMin || "N/A"} - ${job.experienceMax || "N/A"} years</p>
    <p><strong>Salary:</strong> ${job.salaryMin || "N/A"} - ${job.salaryMax || "N/A"} LPA</p>

    <div style="margin-top:16px;padding:12px;background:#ecfeff;border-radius:8px;color:#075985;">
      New opportunity is now live in the system.
    </div>

    <hr style="margin:24px 0;" />

    <p style="font-size:12px;color:#6b7280;text-align:center;">
      Generated by CORE Hiring Engine
    </p>

  </div>
</div>
`;
            try {
              await resend.emails.send({
                from: "Core Team <no-reply@careersatcore.com>",
                to: ["prathamchiragghosh@gmail.com","rajiv.ghoshrajiv@gmail.com"],
                subject: `New Job: ${job.title}`,
                html: emailHtml
              });
          } catch (err) {
            console.error("Mail failed:", err.message);
          } 

  } catch (err) {
    console.error("ERROR:", err);
    res.status(500).json({ error: err.message });
  } finally {
    if (filePath && fs.existsSync(filePath)) {
      fs.unlink(filePath, (err) => {
        if (err) console.error("File delete error:", err.message);
        else console.log("Temp file deleted:", filePath);
      });
    }
  }
};

export const matchCandidatesForJob = async (req, res) => {
  try {
    const { jobId } = req.params;

    const results = await matchJobToCandidates(jobId);

    res.json({
      count: results.length,
      matches: results.map(r => ({
        applicationId: r.candidate._id,
        name: r.candidate.name,
        email: r.candidate.email,
        score: r.score,
        feedback: r.feedback,
        resumeUrl: r.candidate.resumeURL,
        resumeText: r.candidate.resumeText
      }))
    });

  } catch (err) {
    console.error("Job match error:", err);
    res.status(500).json({ error: err.message });
  }
};

export const getAllJobs = async (req, res) => {
  try {
    const jobs = await Job.find().sort({ createdAt: -1 });
    res.json(jobs);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

export const deleteJob = async (req, res) => {
  try {
    const { jobId } = req.params;

    const job = await Job.findByIdAndDelete(jobId);

    if (!job) {
      return res.status(404).json({ error: "Job not found" });
    }

    await PairedScore.deleteMany({ jobId });
    res.json({
      message: "Job deleted successfully",
      jobId
    });

  } catch (err) {
    console.error("Delete job error:", err);
    res.status(500).json({ error: err.message });
  }
};

export const getMyJobs = async (req, res) => {
  try {
    const jobs = await Job.find({
      $or: [
        { recruiterId: req.user.id },
        { recruiterId: { $exists: false } }, // no recruiterId field
        { recruiterId: null } // explicitly null
      ]
    }).sort({ createdAt: -1 });

    res.json(jobs);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

export const getJobById = async (req, res) => {
  try {
    const { jobId } = req.params;

    const job = await Job.findById(jobId);

    if (!job) {
      return res.status(404).json({ error: "Job not found" });
    }

    res.json(job);

  } catch (err) {
    console.error("Get job error:", err);
    res.status(500).json({ error: err.message });
  }
};