import ReportRequest from "../models/ReportRequest.js";
import Report from "../models/Reports.js"; // 🔥 NEW
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export const requestReport = async (req, res) => {
  try {
    const { name, company, email, reportId } = req.body;

    const existing = await ReportRequest.findOne({ email });

    if (existing) {
    return res.status(400).json({
        error: "You have already requested a report"
    });
    }
    const report = await Report.findById(reportId);
    if (!report) {
      return res.status(404).json({ error: "Report not found" });
    }

    // 🔹 save lead
    await ReportRequest.create({
      name,
      company,
      email,
      reportId
    });

    // 🔥 EMAIL WITH ACTUAL REPORT LINK
    const emailHtml = `
<div style="font-family:Arial,sans-serif;background:#f9fafb;padding:24px;">

  <div style="max-width:600px;margin:auto;background:white;border-radius:12px;padding:24px;">

    <h2 style="margin:0;color:#111827;">
      Your Hiring Intelligence Report is Ready
    </h2>

    <hr style="margin:16px 0;border:none;border-top:1px solid #e5e7eb;" />

    <p style="margin:8px 0;color:#374151;">
      Hi ${name},
    </p>

    <p style="margin:8px 0;color:#374151;">
      Thank you for your interest. Here is your requested report:
    </p>

    <div style="background:#f3f4f6;padding:16px;border-radius:8px;margin:16px 0;">
      <p style="margin:0;font-weight:bold;color:#111827;">
        ${report.location} ${report.category} Hiring Intelligence Report
      </p>
    </div>

    <div style="margin:20px 0;text-align:center;">
      <a href="${report.document}"
         style="display:inline-block;padding:12px 20px;background:#ce2029;color:white;text-decoration:none;border-radius:8px;font-weight:bold;">
         Download Report
      </a>
    </div>

    ${
      report.description
        ? `<p style="margin:12px 0;color:#4b5563;line-height:1.5;">
            ${report.description}
           </p>`
        : ""
    }

    <hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb;" />

    <p style="margin:8px 0;color:#374151;">
      Looking to hire similar talent?
    </p>

    <div style="text-align:center;margin-top:12px;">
      <a href="https://jobs.careersatcore.com/client"
         style="display:inline-block;padding:10px 18px;background:#111827;color:white;text-decoration:none;border-radius:6px;">
         Start Hiring
      </a>
    </div>

    <hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb;" />

    <p style="font-size:12px;color:#6b7280;text-align:center;">
      Generated by CORE Hiring Intelligence
    </p>

  </div>
</div>
`;
try {
          await resend.emails.send({
            from: "Core Team <no-reply@careersatcore.com>",
            to: [email],
            subject: `${report.location} ${report.category} Hiring Report`,
            html: emailHtml
          });
        console.log("[ApplicationController] INFO: Match email sent successfully");
      } catch (err) {
        console.error("[ApplicationController] ERROR: Failed to send match email:", err.message);
      }
    
    
    res.json({ success: true });

  } catch (err) {
    console.error("Report request error:", err);
    res.status(500).json({ error: err.message });
  }
};